{{- if .Values.github.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pi-runner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pi-runner.labels" . | nindent 4 }}
type: Opaque
stringData:
  github-token: {{ .Values.github.token | quote }}
{{- end }}
